#!/usr/bin/env bash
################################################################################
# Filename: wmake
#
# This script runs "make" (or "ninja") when a file changes.
################################################################################

# Make sure we're more strict about execution.
set -o errexit
set -o pipefail
set -o nounset

# Prints the help message and exist
help()
{
    exec 1>&2
    echo "wmake"
    echo "    -m, --make <makeprg>"
    echo "        The program to execute after a period of inactivity."
    echo "        By default, this is 'ninja'."
    exit $1
}

# Set some common variables.
makeprg=

# Parse the command line arguments.
while [ $# -gt 0 ] ; do
    case "$1" in
        -h | --help)
            help 1
            ;;
        -m | --make)
            makeprg="${2:-}"
            shift
            ;;
        *)
            echo "Unknown command." >&2
            exit 1
            ;;
    esac

    shift
done

if [ -z "$makeprg" ] ; then
    if [ -f Makefile ] ; then
        makeprg=make
    else
        makeprg=ninja
    fi
fi

# Infinite loop, calling wexec.
while true ; do
    inotifywait --exclude ninja -r -m -q -e close_write --format %f . | wexec -s 0 -n 333333333 -c "$makeprg"
done

